# Generated by Django 5.1.1 on 2024-10-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_image_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('on_the_road', 'On the Road'), ('not_available', 'Not Available')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_clothes',
            field=models.TextField(default='Unknown'),
        ),
    ]
