# Generated by Django 5.1 on 2025-01-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='materials',
        ),
    ]
