# Generated by Django 5.1.1 on 2024-10-04 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 21, 54, 34, 240702, tzinfo=datetime.timezone.utc)),
        ),
    ]
