# Generated by Django 5.1.1 on 2024-10-05 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 20, 25, 40, 242781, tzinfo=datetime.timezone.utc)),
        ),
    ]
