# Generated by Django 5.1 on 2025-01-18 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating_alter_reviewproduct_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
